grafana:
  enabled: true

  adminUser: admin

  persistence:
    enabled: true
    size: 1Gi

  service:
    type: ClusterIP

  defaultDashboardsEnabled: true

  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 300m